spring:
  ai:
    model:
      embedding: ollama
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text
      init:
        pull-model-strategy: when_missing
        timeout: 60s

recs:
  limit: 5