server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: booking-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/catchmyshow?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Kolkata&useSSL=false}
    username: ${DB_USER:cms}
    password: ${DB_PASS:cms}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
        highlight_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  lifecycle:
    timeout-per-shutdown-phase: 20s
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASS:admin}

management:
  endpoints:
    web:
      exposure:
        include: [health, info, mappings]
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
      probes:
        enabled: true

logging:
  level:
    org.hibernate.SQL: warn
    org:
      springframework:
        web:
          method: INFO
      springdoc: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN
    org.springframework.dao: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.transaction: DEBUG
    com.zaxxer.hikari: INFO

springdoc:
  use-fqn: true



